data:
  intro:
    -  val: 蒋正兴
       key: name
    -  val: medianeras57@gmail.com
       key: email
    -  val: 毕业于重庆邮电大学，软件工程学院
       key: graduate
  resume:
      skill:
         title: 掌握技能
         val: 
          -  熟悉html，css，javascript；
          -  熟练掌握photoshop切图；熟悉Git常用命令；
          -  了解Nodejs，react，vuejs，并都有上线项目；
          -  了解移动端开发，并有线上项目；
          -  了解小程序开发
         key: skill
      experience: 
       -  company: 重庆猪八戒网络有限公司
          time: 2015年9月-2016年4月（实习）
          department: 广告取经团
          content: 熟悉公司前端技术架构，在带领下维护老页面，期间还参与图片广告系统的开发
          key: zhubajie00
          skills: 
            -  jQuery
            -  smarty
       -  company: 重庆猪八戒网络有限公司
          time: 2016年6月-2017年6月
          department: 增值广告事业部
          content: 正式加入重庆猪八戒网络有限公司，期间前端技术架构调整，公司开始使用Nodejs作为中间层，老页面仍然主要使用jQuery，新产品开发使用Nodejs和java对接，同时面向内部的管理系统使用vue进行开发，基于饿了么前端组件搭建。期间主要负责部门面向用户向主站投放图片广告的产品以及面向内部使用的后台管理系统开发，主要产品有<a href="https://xw.zbj.com/">八戒仙位</a>，<a href="http://modimall.zbj.com/">魔笛</a>，关键词投放，以及相应的后台管理系统，同时还与外站汉仪字库合作，内嵌他们的页面进行推广，此外以及其他老页面和少许专题页的维护与开发。
          key: zhubajie01
          skills:
            -  Nodejs
            -  Vuejs
            -  nujucks
            -  lite
            -  jQuery
       -  company: 杭州以息互联网科技有限公司
          time: 2017年6月-至今
          department: ''
          content: 目前为止调整了公司前端的技术栈（虽然只有我一个前端）,从以前的jQuery老页面调整到现在接入Nodejs，react，vuejs，在交互和性能进行了改进，期间使用vuejs重构了后台管理系统，使用react+nextjs重构了app内<a href="https://api.c2h4.org/show/article/579">文章页面</a>，使用ssr提高性能，以及使用react和canvas开发<a href="https://fun.c2h4.org/">活动h5页面</a>和老页面维护
          key: yixi
          skills:
            -  Nodejs
            -  react
            -  vuejs
            -  jQuery
