data:
  intro:
    -  val: 蒋正兴
       key: name
    -  val: '18203096625'
       key: phone
    -  val: medianeras57@gmail.com
       key: email
    -  val: 毕业于重庆邮电大学，软件工程学院
       key: graduate
    -  val: <a href="https://github.com/Neras">https://github.com/Neras</a>
       key: github
   #  -  val: <a href="https://neras.github.io">https://neras.github.io</a>
   #     key: blog
  resume:
      skill:
         title: 掌握技能
         val: 
          -  熟悉html，理解Web语义化，理解盒子模型，手写符合W3C标准的css代码
          -  熟悉JavaScript，掌握ES6/7，并运用到实际项目中
          -  熟悉Git常用命令；
          -  熟练使用Photoshop切图应该是基本之一
          -  熟悉React
          -  了解Nodejs，Vue，并都有线上项目；
          -  了解移动端开发，并有线上项目；
          -  了解Docker
          -  有简单的Nginx部署Nodejs项目经验
         key: skill
      experience: 
        -  company: 杭州火烧云科技有限公司
           time: 2018年5月-至今
           department: 研发部门
           projects: 
            -  使用React, mobx和antd-design维护、开发公司后台管理系统
            -  使用React + mobx开发面向用户的<a href="https://www.hunliji.com/p/wedding/Public/admin/local_merchant_react/dist/index.html#/localMerchant/home">商家后台</a>
            -  使用React + mobx开发<a href="https://www.hunliji.com/p/wedding/Public/admin/desktop_app_set/dist/index.html#/index"> 水镜系统 可视化配置页面</a>
            -  使用vue开发维护内嵌APP的页面
            -  尝试使用Vue ssr重构移动端首页
            -  尝试使用Node.js进行服务端开发，拉新活动项目
            -  尝试使用Docker进行前端的CI
           key: hunliji
           skills: 
            -  React
            -  mobx
            -  Vue
            -  Node.js
        -  company: 杭州以息互联网科技有限公司
           time: 2017年6月-2018年3月
           department: ''
           projects:
             -  维护jQuery老项目，同时使用的Nodejs，Reactjs，Vue进行新项目的开发
             -  与百度合作，将人脸检测功能提取嵌入百度，<a href="https://open.c2h4.org/c2h42baidu/#/">https://open.c2h4.org/c2h42baidu/#/</a>
             -  使用Vue重构公司后台管理系统，基于饿了么前端组件搭建
             -  构建小程序内使用的APP主要功能模块，供外部使用
             -  使用React+nextjs重构APP内的<a href="https://api.c2h4.org/show/article/579">文章页面</a>，添加功能的同时加快页面渲染
             -  使用React和canvas开发<a href="https://fun.c2h4.org/">活动h5页面</a> 
           key: yixi
           skills:
             -  Node.js
             -  React
             -  nextjs
             -  Vue
             -  jQuery
        -  company: 重庆猪八戒网络有限公司
           time: 2016年6月-2017年6月
           department: 增值广告事业部
           projects:
             -  负责<a href="https://xw.zbj.com/">八戒仙位</a>开发，使用fis3构建，主要编写供同事使用的公共组件
             -  负责<a href="https://ppb.zbj.com">品牌宝</a>开发，仍以Nodejs作为中间层与java对接
             -  参与部门后台管理系统开发，公共组件的构建以及维护
             -  参与与外站汉仪字库合作的开发，内嵌他们页面进行推广
             -  少许专题页开发以及老页面维护
           key: zhubajie01
           skills:
             -  Node.js
             -  Vue
             -  nunjucks
             -  lite
             -  jQuery
             -  smarty
  evaluation: 
    -  深知只有不断学习才能走得更远，初入猪八戒时，曾获得部门年中<b>最佳进步奖</b>
    -  愿意并且喜欢去认识新的事物，在猪八戒时，在大规范的范围下仍然尝试如何使用ES6/7的新特性
    -  愿意折腾，用自己的vps做一做看一看墙内无法做的事情
    -  足够的耐心与清晰的思维应该是一个程序员的标配。特立独行或许能让人拥有一个有趣的灵魂，但是遵守规范才能使大家更好的协同工作。
    -  清晰的认识到自己现在缺乏什么，该去寻找什么。
    -  简历源代码<a href="https://github.com/Neras/nextjs-resume">https://github.com/Neras/nextjs-resume</a>
